{
  "swagger": "2.0",
  "info": {
    "title": "Mojaloop Auth-Service API",
    "version": "0.1.0",
    "description": "An API a central auth service in Mojaloop, concerned with creating \\nand managing Consents and validating thirdparty transactions",
    "license": {
      "name": "Open API for FSP Interoperability (FSPIOP) (Implementation Friendly Version)"
    }
  },
  "basePath": "/",
  "schemes": [
    "http"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/health": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "health"
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/ResponseHealth200"
          },
          "400": {
            "$ref": "#/responses/ErrorResponse400"
          },
          "401": {
            "$ref": "#/responses/ErrorResponse401"
          },
          "403": {
            "$ref": "#/responses/ErrorResponse403"
          },
          "404": {
            "$ref": "#/responses/ErrorResponse404"
          },
          "405": {
            "$ref": "#/responses/ErrorResponse405"
          },
          "406": {
            "$ref": "#/responses/ErrorResponse406"
          },
          "501": {
            "$ref": "#/responses/ErrorResponse501"
          },
          "503": {
            "$ref": "#/responses/ErrorResponse503"
          }
        },
        "operationId": "HealthGet",
        "summary": "Get Server",
        "description": "The HTTP request GET /health is used to return the current status of the API."
      }
    },
    "/metrics": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "metrics"
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/ResponseHealth200"
          },
          "400": {
            "$ref": "#/responses/ErrorResponse400"
          },
          "401": {
            "$ref": "#/responses/ErrorResponse401"
          },
          "403": {
            "$ref": "#/responses/ErrorResponse403"
          },
          "404": {
            "$ref": "#/responses/ErrorResponse404"
          },
          "405": {
            "$ref": "#/responses/ErrorResponse405"
          },
          "406": {
            "$ref": "#/responses/ErrorResponse406"
          },
          "501": {
            "$ref": "#/responses/ErrorResponse501"
          },
          "503": {
            "$ref": "#/responses/ErrorResponse503"
          }
        },
        "operationId": "MetricsGet",
        "summary": "Prometheus metrics endpoint",
        "description": "The HTTP request GET /metrics is used to return metrics for the API."
      }
    },
    "/hello": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "metrics"
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/ResponseHealth200"
          },
          "400": {
            "$ref": "#/responses/ErrorResponse400"
          },
          "401": {
            "$ref": "#/responses/ErrorResponse401"
          },
          "403": {
            "$ref": "#/responses/ErrorResponse403"
          },
          "404": {
            "$ref": "#/responses/ErrorResponse404"
          },
          "405": {
            "$ref": "#/responses/ErrorResponse405"
          },
          "406": {
            "$ref": "#/responses/ErrorResponse406"
          },
          "501": {
            "$ref": "#/responses/ErrorResponse501"
          },
          "503": {
            "$ref": "#/responses/ErrorResponse503"
          }
        },
        "operationId": "HelloGet",
        "summary": "example get",
        "description": "The HTTP request GET /hello is used to return some example json."
      }
    },
    "/consents": {
      "post": {
        "description": "The HTTP request `POST /consents` is used to create a consent object. \n\n- Called by `DFSP` after the succesful creation and validation of a consentRequest.\n",
        "summary": "CreateConsent",
        "tags": [
          "consent"
        ],
        "operationId": "CreateConsent",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Consent"
            }
          },
          {
            "$ref": "#/parameters/Content-Length"
          },
          {
            "$ref": "#/parameters/Content-Type"
          },
          {
            "$ref": "#/parameters/Date"
          },
          {
            "$ref": "#/parameters/X-Forwarded-For"
          },
          {
            "$ref": "#/parameters/FSPIOP-Source"
          },
          {
            "$ref": "#/parameters/FSPIOP-Destination"
          },
          {
            "$ref": "#/parameters/FSPIOP-Encryption"
          },
          {
            "$ref": "#/parameters/FSPIOP-Signature"
          },
          {
            "$ref": "#/parameters/FSPIOP-URI"
          },
          {
            "$ref": "#/parameters/FSPIOP-HTTP-Method"
          }
        ],
        "x-examples": {
          "application/json": {
            "id": "123",
            "requestId": "456",
            "initiatorId": "pispa",
            "participantId": "dfspa",
            "scopes": [
              {
                "scope": "account.balanceInquiry",
                "accountId": "dfspa.alice.1234"
              },
              {
                "scope": "account.sendTransfer",
                "accountId": "dfspa.alice.1234"
              },
              {
                "scope": "account.sendTransfer",
                "accountId": "dfspa.alice.5678"
              }
            ],
            "credential": null
          }
        },
        "responses": {
          "202": {
            "$ref": "#/responses/Response202"
          },
          "400": {
            "$ref": "#/responses/ErrorResponse400"
          },
          "401": {
            "$ref": "#/responses/ErrorResponse401"
          },
          "403": {
            "$ref": "#/responses/ErrorResponse403"
          },
          "404": {
            "$ref": "#/responses/ErrorResponse404"
          },
          "405": {
            "$ref": "#/responses/ErrorResponse405"
          },
          "406": {
            "$ref": "#/responses/ErrorResponse406"
          },
          "501": {
            "$ref": "#/responses/ErrorResponse501"
          },
          "503": {
            "$ref": "#/responses/ErrorResponse503"
          }
        }
      }
    },
    "/consents/{ID}": {
      "parameters": [
        {
          "$ref": "#/parameters/ID"
        },
        {
          "$ref": "#/parameters/Content-Type"
        },
        {
          "$ref": "#/parameters/Date"
        },
        {
          "$ref": "#/parameters/X-Forwarded-For"
        },
        {
          "$ref": "#/parameters/FSPIOP-Source"
        },
        {
          "$ref": "#/parameters/FSPIOP-Destination"
        },
        {
          "$ref": "#/parameters/FSPIOP-Encryption"
        },
        {
          "$ref": "#/parameters/FSPIOP-Signature"
        },
        {
          "$ref": "#/parameters/FSPIOP-URI"
        },
        {
          "$ref": "#/parameters/FSPIOP-HTTP-Method"
        }
      ],
      "get": {
        "description": "The HTTP request `GET /consents/{ID}` is used to get information regarding a consent object created or requested earlier.  The `{ID}` in the URI should contain the `{ID}` that was used in the `POST /consents`.\n",
        "summary": "GetConsent",
        "tags": [
          "consent"
        ],
        "operationId": "GetConsent",
        "parameters": [
          {
            "$ref": "#/parameters/Accept"
          }
        ],
        "responses": {
          "202": {
            "$ref": "#/responses/Response202"
          },
          "400": {
            "$ref": "#/responses/ErrorResponse400"
          },
          "401": {
            "$ref": "#/responses/ErrorResponse401"
          },
          "403": {
            "$ref": "#/responses/ErrorResponse403"
          },
          "404": {
            "$ref": "#/responses/ErrorResponse404"
          },
          "405": {
            "$ref": "#/responses/ErrorResponse405"
          },
          "406": {
            "$ref": "#/responses/ErrorResponse406"
          },
          "501": {
            "$ref": "#/responses/ErrorResponse501"
          },
          "503": {
            "$ref": "#/responses/ErrorResponse503"
          }
        }
      },
      "put": {
        "description": "The HTTP request `PUT /consents/{ID}` is used to update a specified consent object. \nThe `{ID}` in the URI should contain the `{ID}` that was used in the `POST /consents`.\n\n- Called by a `auth-service` to add the credential details\n\n- Called by a `PISP` to add a signature of the challenge\n",
        "summary": "UpdateConsent",
        "tags": [
          "consent"
        ],
        "operationId": "UpdateConsent",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Consent"
            }
          },
          {
            "$ref": "#/parameters/Content-Length"
          }
        ],
        "x-examples": {
          "application/json": {
            "requestId": "456",
            "initiatorId": "dfspa",
            "participantId": "pispa",
            "scopes": [
              {
                "scope": "account.balanceInquiry",
                "accountId": "dfspa.alice.1234"
              },
              {
                "scope": "account.sendTransfer",
                "accountId": "dfspa.alice.1234"
              },
              {
                "scope": "account.sendTransfer",
                "accountId": "dfspa.alice.5678"
              }
            ],
            "credential": {
              "id": "5678",
              "credentialType": "FIDO",
              "credentialStatus": "ACTIVE",
              "challenge": {
                "payload": "base64(...)",
                "signature": "base64(...)"
              },
              "payload": "base64(...)"
            }
          }
        },
        "responses": {
          "202": {
            "$ref": "#/responses/Response202"
          },
          "400": {
            "$ref": "#/responses/ErrorResponse400"
          },
          "401": {
            "$ref": "#/responses/ErrorResponse401"
          },
          "403": {
            "$ref": "#/responses/ErrorResponse403"
          },
          "404": {
            "$ref": "#/responses/ErrorResponse404"
          },
          "405": {
            "$ref": "#/responses/ErrorResponse405"
          },
          "406": {
            "$ref": "#/responses/ErrorResponse406"
          },
          "501": {
            "$ref": "#/responses/ErrorResponse501"
          },
          "503": {
            "$ref": "#/responses/ErrorResponse503"
          }
        }
      }
    },
    "/consents/{ID}/generateChallenge": {
      "post": {
        "description": "The HTTP request `POST /consents/{ID}/generateChallenge` is used to create a credential for the given Consent object. \nThe `{ID}` in the URI should contain the `{ID}` that was used in the `POST /consents`.\n\n- Called by a `PISP` to request a challenge from the `auth-service`, which will be returned to the PISP via `PUT /consents/{ID}`\n",
        "summary": "GenerateChallengeRequest",
        "tags": [
          "consent"
        ],
        "operationId": "GenerateChallengeRequest",
        "parameters": [
          {
            "$ref": "#/parameters/ID"
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/GenerateChallengeRequest"
            }
          },
          {
            "$ref": "#/parameters/Content-Length"
          },
          {
            "$ref": "#/parameters/Content-Type"
          },
          {
            "$ref": "#/parameters/Date"
          },
          {
            "$ref": "#/parameters/X-Forwarded-For"
          },
          {
            "$ref": "#/parameters/FSPIOP-Source"
          },
          {
            "$ref": "#/parameters/FSPIOP-Destination"
          },
          {
            "$ref": "#/parameters/FSPIOP-Encryption"
          },
          {
            "$ref": "#/parameters/FSPIOP-Signature"
          },
          {
            "$ref": "#/parameters/FSPIOP-URI"
          },
          {
            "$ref": "#/parameters/FSPIOP-HTTP-Method"
          }
        ],
        "x-examples": {
          "application/json": {}
        },
        "responses": {
          "202": {
            "$ref": "#/responses/Response202"
          },
          "400": {
            "$ref": "#/responses/ErrorResponse400"
          },
          "401": {
            "$ref": "#/responses/ErrorResponse401"
          },
          "403": {
            "$ref": "#/responses/ErrorResponse403"
          },
          "404": {
            "$ref": "#/responses/ErrorResponse404"
          },
          "405": {
            "$ref": "#/responses/ErrorResponse405"
          },
          "406": {
            "$ref": "#/responses/ErrorResponse406"
          },
          "501": {
            "$ref": "#/responses/ErrorResponse501"
          },
          "503": {
            "$ref": "#/responses/ErrorResponse503"
          }
        }
      }
    },
    "/thirdPartyRequests/transactions/{ID}/authorizations": {
      "post": {
        "description": "The HTTP request `POST /thirdPartyRequests/transactions/{id}/authorizations` is called by\nthe DFSP to check that a ThirdPartyRequest is valid\n",
        "summary": "ThirdpartyAuthorizationRequest",
        "tags": [
          "thirdPartyRequests"
        ],
        "operationId": "VerifyThirdPartyAuthorization",
        "parameters": [
          {
            "$ref": "#/parameters/ID"
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/ThirdPartyAuthorizationRequest"
            }
          },
          {
            "$ref": "#/parameters/Accept"
          },
          {
            "$ref": "#/parameters/Content-Length"
          },
          {
            "$ref": "#/parameters/Content-Type"
          },
          {
            "$ref": "#/parameters/Date"
          },
          {
            "$ref": "#/parameters/X-Forwarded-For"
          },
          {
            "$ref": "#/parameters/FSPIOP-Source"
          },
          {
            "$ref": "#/parameters/FSPIOP-Destination"
          },
          {
            "$ref": "#/parameters/FSPIOP-Encryption"
          },
          {
            "$ref": "#/parameters/FSPIOP-Signature"
          },
          {
            "$ref": "#/parameters/FSPIOP-URI"
          },
          {
            "$ref": "#/parameters/FSPIOP-HTTP-Method"
          }
        ],
        "x-examples": {
          "application/json": {
            "challenge": "<QuoteResponse object>",
            "value": "<base64 encoded binary - the signed quote response object>",
            "consentId": "111",
            "sourceAccountId": "dfspa.1111-2222",
            "status": "PENDING"
          }
        },
        "responses": {
          "202": {
            "$ref": "#/responses/Response202"
          },
          "400": {
            "$ref": "#/responses/ErrorResponse400"
          },
          "401": {
            "$ref": "#/responses/ErrorResponse401"
          },
          "403": {
            "$ref": "#/responses/ErrorResponse403"
          },
          "404": {
            "$ref": "#/responses/ErrorResponse404"
          },
          "405": {
            "$ref": "#/responses/ErrorResponse405"
          },
          "406": {
            "$ref": "#/responses/ErrorResponse406"
          },
          "501": {
            "$ref": "#/responses/ErrorResponse501"
          },
          "503": {
            "$ref": "#/responses/ErrorResponse503"
          }
        }
      }
    }
  },
  "definitions": {
    "AccountAddress": {
      "title": "AccountAddress",
      "type": "string",
      "description": "Unique routable address which is DFSP specific.",
      "pattern": "^([0-9A-Za-z_~\\-\\.]+[0-9A-Za-z_~\\-])$",
      "minLength": 1,
      "maxLength": 1023
    },
    "AccountId": {
      "type": "string",
      "description": "A long-lived account identifier provided by the DFSP this MUST NOT be Bank Account Number or anything that may expose a User's private bank account information\n"
    },
    "AuthScopesEnum": {
      "title": "AuthScopesEnum",
      "type": "string",
      "enum": [
        "accounts.getBalance",
        "accounts.transfer"
      ],
      "description": "The scopes requested for a ConsentRequest\n- \"accounts.getBalance\" - Get the balance of a given account\n- \"accounts.transfer\" - initiate a transfer from an account\n"
    },
    "Consent": {
      "title": "Consent",
      "type": "object",
      "description": "Data model for the complex type Consent",
      "properties": {
        "id": {
          "allOf": [
            {
              "$ref": "#/definitions/CorrelationId"
            }
          ],
          "description": "Common ID between the PISP and FSP for the Consent object decided by the DFSP who creates the Consent\nThis field is REQUIRED for POST /consent\n"
        },
        "requestId": {
          "allOf": [
            {
              "$ref": "#/definitions/CorrelationId"
            }
          ],
          "description": "The id of the ConsentRequest that was used to initiate the creation of this Consent\n"
        },
        "participantId": {
          "$ref": "#/definitions/FspId"
        },
        "initiatorId": {
          "allOf": [
            {
              "$ref": "#/definitions/FspId"
            }
          ],
          "description": "PISP identifier who uses this Consent"
        },
        "scopes": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Scope"
          }
        },
        "credential": {
          "$ref": "#/definitions/Credential"
        }
      }
    },
    "Credential": {
      "title": "Credential",
      "type": "object",
      "description": "A credential used to allow a user to prove their identity and access to an account with a DFSP\n",
      "properties": {
        "id": {
          "type": "string",
          "description": "The id of a Credential"
        },
        "type": {
          "$ref": "#/definitions/CredentialTypeEnum"
        },
        "status": {
          "$ref": "#/definitions/CredentialStatusEnum"
        },
        "challenge": {
          "$ref": "#/definitions/CredentialChallenge"
        },
        "payload": {
          "type": "string",
          "description": "Base64 encoded bytes - The public key of the Public/Private keypair"
        }
      },
      "required": [
        "id",
        "type",
        "status"
      ]
    },
    "GenerateChallengeRequest": {
      "title": "GenerateChallengeRequest",
      "type": "object",
      "description": "A credential used to allow a user to prove their identity and access to an account with a DFSP\n",
      "properties": {
        "type": {
          "$ref": "#/definitions/CredentialTypeEnum"
        }
      },
      "required": [
        "type"
      ]
    },
    "CredentialChallenge": {
      "title": "CredentialChallenge",
      "type": "object",
      "description": "The challenge issued by a DFSP that must be answered by the PISP\n",
      "properties": {
        "payload": {
          "type": "string",
          "description": "Base64 encoded binary of the challenge that must be answered by the PISP"
        },
        "signature": {
          "type": "string",
          "description": "Base64 enoded binary string or result of the payload signed by the PISP using the private key"
        }
      },
      "required": [
        "payload"
      ]
    },
    "CredentialStatusEnum": {
      "title": "CredentialStatus",
      "type": "string",
      "enum": [
        "PENDING",
        "ACTIVE"
      ],
      "description": "The status of the Credential's creation\n- \"PENDING\" - The PISP has requested a challenge, or the challenge has initialized but not yet answered by the PISP\n- \"ACTIVE\" - The Credential is valid, and ready to be used by the PISP\n"
    },
    "CredentialTypeEnum": {
      "title": "CredentialTypeEnum",
      "type": "string",
      "enum": [
        "FIDO"
      ],
      "description": "The type of the Credential\n- \"FIDO\" - A FIDO public/private keypair\n"
    },
    "Scope": {
      "title": "Scope",
      "type": "object",
      "description": "Scope + Account Identifier mapping for a Consent",
      "properties": {
        "scope": {
          "$ref": "#/definitions/AuthScopesEnum"
        },
        "accountId": {
          "$ref": "#/definitions/AccountId"
        }
      },
      "required": [
        "scope",
        "accountId"
      ]
    },
    "ThirdPartyAuthorizationRequest": {
      "title": "ThirdPartyAuthorizationRequest",
      "type": "object",
      "description": "The Request object for verifying an authorization",
      "properties": {
        "challenge": {
          "type": "string",
          "description": "The original Challenge (Quote response) object as a JSON string"
        },
        "value": {
          "type": "string",
          "description": "The signed Challenge (quote response) object as base64 encoded string"
        },
        "consentId": {
          "allOf": [
            {
              "$ref": "#/definitions/CorrelationId"
            }
          ],
          "description": "Common ID between the PISP and FSP for the Consent object decided by the DFSP who creates the Consent\n"
        },
        "sourceAccountId": {
          "allOf": [
            {
              "$ref": "#/definitions/AccountId"
            }
          ]
        },
        "status": {
          "type": "string",
          "enum": [
            "PENDING",
            "VERIFIED"
          ],
          "description": "The transaction signature verification status"
        }
      },
      "required": [
        "challenge",
        "value",
        "consentId",
        "sourceAccountId",
        "status"
      ]
    },
    "BinaryString": {
      "description": "The API data type BinaryString is a JSON String. The string is a base64url  encoding of a string of raw bytes, where padding (character ‘=’) is added at the end of the data if needed to ensure that the string is a multiple of 4 characters. The length restriction indicates the allowed number of characters.",
      "pattern": "^[A-Za-z0-9-_]+[=]{0,2}$",
      "type": "string"
    },
    "BinaryString32": {
      "description": "The API data type BinaryString32 is a fixed size version of the API data type BinaryString, where the raw underlying data is always of 32 bytes. The data type BinaryString32 should not use a padding character as the size of the underlying data is fixed.",
      "pattern": "^[A-Za-z0-9-_]{43}$",
      "type": "string"
    },
    "CorrelationId": {
      "title": "CorrelationId",
      "description": "Identifier that correlates all messages of the same sequence. The API data type UUID (Universally Unique Identifier) is a JSON String in canonical format, conforming to RFC 4122, that is restricted by a regular expression for interoperability reasons. An UUID is always 36 characters long, 32 hexadecimal symbols and 4 dashes (‘-‘).",
      "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
      "type": "string"
    },
    "Date": {
      "title": "Date",
      "description": "The API data type Date is a JSON String in a lexical format that is restricted by a regular expression for interoperability reasons. This format, as specified in ISO 8601, contains a date only. A more readable version of the format is yyyy-MM-dd. Examples - \"1982-05-23\", \"1987-08-05”",
      "pattern": "^(?:[1-9]\\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)$",
      "type": "string"
    },
    "DateTime": {
      "title": "DateTime",
      "description": "The API data type DateTime is a JSON String in a lexical format that is restricted by a regular expression for interoperability reasons. The format is according to ISO 8601, expressed in a combined date, time and time zone format. A more readable version of the format is yyyy-MM-ddTHH:mm:ss.SSS[-HH:MM]. Examples -  \"2016-05-24T08:38:08.699-04:00\", \"2016-05-24T08:38:08.699Z\" (where Z indicates Zulu time zone, same as UTC).",
      "pattern": "^(?:[1-9]\\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)T(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:(\\.\\d{3}))(?:Z|[+-][01]\\d:[0-5]\\d)$",
      "type": "string"
    },
    "ErrorCode": {
      "title": "ErrorCode",
      "description": "The API data type ErrorCode is a JSON String of four characters, consisting of digits only. Negative numbers are not allowed. A leading zero is not allowed. Each error code in the API is a four-digit number, for example, 1234, where the first number (1 in the example) represents the high-level error category, the second number (2 in the example) represents the low-level error category, and the last two numbers (34 in the example) represents the specific error.",
      "pattern": "^[1-9]\\d{3}$",
      "type": "string"
    },
    "ErrorDescription": {
      "title": "ErrorDescription",
      "description": "Error description string.",
      "maxLength": 128,
      "minLength": 1,
      "type": "string"
    },
    "ExtensionKey": {
      "title": "ExtensionKey",
      "description": "Extension key.",
      "maxLength": 32,
      "minLength": 1,
      "type": "string"
    },
    "ExtensionValue": {
      "title": "ExtensionValue",
      "description": "Extension value.",
      "maxLength": 128,
      "minLength": 1,
      "type": "string"
    },
    "FspId": {
      "title": "FspId",
      "description": "FSP identifier.",
      "maxLength": 32,
      "minLength": 1,
      "type": "string"
    },
    "Integer": {
      "title": "Integer",
      "description": "The API data type Integer is a JSON String consisting of digits only. Negative numbers and leading zeroes are not allowed. The data type is always limited to a specific number of digits.",
      "pattern": "^[1-9]\\d*$",
      "type": "string"
    },
    "ErrorInformation": {
      "title": "ErrorInformation",
      "description": "Data model for the complex type ErrorInformation.",
      "required": [
        "errorCode",
        "errorDescription"
      ],
      "type": "object",
      "properties": {
        "errorCode": {
          "description": "Specific error number.",
          "type": "string"
        },
        "errorDescription": {
          "description": "Error description string.",
          "type": "string"
        },
        "extensionList": {
          "$ref": "#/definitions/ExtensionList",
          "description": "Optional list of extensions, specific to deployment."
        }
      }
    },
    "ErrorInformationObject": {
      "title": "ErrorInformationObject",
      "description": "Data model for the complex type object that contains ErrorInformation.",
      "required": [
        "errorInformation"
      ],
      "type": "object",
      "properties": {
        "errorInformation": {
          "$ref": "#/definitions/ErrorInformation"
        }
      }
    },
    "ErrorInformationResponse": {
      "title": "ErrorInformationResponse",
      "description": "Data model for the complex type object that contains an optional element ErrorInformation used along with 4xx and 5xx responses.",
      "type": "object",
      "properties": {
        "errorInformation": {
          "$ref": "#/definitions/ErrorInformation"
        }
      }
    },
    "Extension": {
      "title": "Extension",
      "description": "Data model for the complex type Extension",
      "required": [
        "key",
        "value"
      ],
      "type": "object",
      "properties": {
        "key": {
          "description": "Extension key.",
          "type": "string"
        },
        "value": {
          "description": "Extension value.",
          "type": "string"
        }
      }
    },
    "ExtensionList": {
      "title": "ExtensionList",
      "description": "Data model for the complex type ExtensionList",
      "required": [
        "extension"
      ],
      "type": "object",
      "properties": {
        "extension": {
          "description": "Number of Extension elements",
          "maxItems": 16,
          "minItems": 1,
          "type": "array",
          "items": {
            "$ref": "#/definitions/Extension"
          }
        }
      }
    },
    "Status": {
      "title": "Status",
      "description": "Data model for the api status.",
      "type": "object",
      "properties": {
        "status": {
          "description": "The return status, usually \"OK\"",
          "type": "string"
        },
        "uptime": {
          "description": "The amount of time in seconds that the server has been up for.",
          "type": "number"
        },
        "startTime": {
          "description": "The UTC time that the server started up",
          "type": "string"
        },
        "versionNumber": {
          "description": "Current version of the API",
          "type": "string"
        },
        "services": {
          "description": "An list of the statuses of services that the API requires",
          "type": "array",
          "items": {}
        }
      }
    }
  },
  "parameters": {
    "Accept": {
      "name": "accept",
      "description": "The Accept header field indicates the version of the API the client would like the server to use.",
      "in": "header",
      "required": true,
      "type": "string"
    },
    "Content-Length": {
      "name": "content-length",
      "description": "The Content-Length header field indicates the anticipated size of the payload body. Only sent if there is a body. Note - The API supports a maximum size of 5242880 bytes (5 Megabytes)",
      "in": "header",
      "required": false,
      "type": "integer"
    },
    "Content-Type": {
      "name": "content-type",
      "description": "The Content-Type header indicates the specific version of the API used to send the payload body.",
      "in": "header",
      "required": true,
      "type": "string"
    },
    "Date": {
      "name": "date",
      "description": "The Date header field indicates the date when the request was sent.",
      "in": "header",
      "required": true,
      "type": "string"
    },
    "X-Forwarded-For": {
      "name": "x-forwarded-for",
      "description": "The X-Forwarded-For header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple X-Forwarded-For values as in the example shown here should be expected and supported by implementers of the API. Note - An alternative to X-Forwarded-For is defined in RFC 7239. However, to this point RFC 7239 is less-used and supported than X-Forwarded-For.",
      "in": "header",
      "required": false,
      "type": "string"
    },
    "FSPIOP-Source": {
      "name": "fspiop-source",
      "description": "The FSPIOP-Source header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field FSPIOP-Signature).",
      "in": "header",
      "required": true,
      "type": "string"
    },
    "FSPIOP-Destination": {
      "name": "fspiop-destination",
      "description": "The FSPIOP-Destination header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field should be set by the original sender of the request (if known), so that any entities between the client and the server do not need to parse the payload for routing purposes.",
      "in": "header",
      "required": false,
      "type": "string"
    },
    "FSPIOP-Originator": {
      "name": "fspiop-originator",
      "description": "The FSPIOP-Originator header field is a non-HTTP standard field used by the API for HTTP header based routing and verification of requests originated from PISP participant. The field should be set by the original PISP sender of the request (if known) to clearly identify that PISP is request's originator",
      "in": "header",
      "required": false,
      "type": "string"
    },
    "FSPIOP-Encryption": {
      "name": "fspiop-encryption",
      "description": "The FSPIOP-Encryption header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request.",
      "in": "header",
      "required": false,
      "type": "string"
    },
    "FSPIOP-Signature": {
      "name": "fspiop-signature",
      "description": "The FSPIOP-Signature header field is a non-HTTP standard field used by the API for applying an end-to-end request signature.",
      "in": "header",
      "required": false,
      "type": "string"
    },
    "FSPIOP-URI": {
      "name": "fspiop-uri",
      "description": "The FSPIOP-URI header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information see API Signature document.",
      "in": "header",
      "required": false,
      "type": "string"
    },
    "FSPIOP-HTTP-Method": {
      "name": "fspiop-http-method",
      "description": "The FSPIOP-HTTP-Method header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information see API Signature document.",
      "in": "header",
      "required": false,
      "type": "string"
    },
    "ID": {
      "name": "ID",
      "in": "path",
      "required": true,
      "type": "string"
    },
    "Type": {
      "name": "Type",
      "in": "path",
      "required": true,
      "type": "string"
    },
    "SubId": {
      "name": "SubId",
      "in": "path",
      "required": true,
      "type": "string"
    }
  },
  "responses": {
    "ResponseHealth200": {
      "description": "OK",
      "schema": {
        "$ref": "#/definitions/Status"
      }
    },
    "ResponseHello200": {
      "description": "example hello-word response",
      "schema": {
        "type": "object",
        "properties": {
          "hello": {
            "type": "string"
          }
        }
      }
    },
    "Response200": {
      "description": "OK"
    },
    "Response202": {
      "description": "Accepted"
    },
    "ErrorResponse400": {
      "description": "Bad Request - The application cannot process the request; for example, due to malformed syntax or the payload exceeded size restrictions.",
      "headers": {
        "Content-Length": {
          "description": "The Content-Length header field indicates the anticipated size of the payload body. Only sent if there is a body.",
          "type": "integer"
        },
        "Content-Type": {
          "description": "The Content-Type header indicates the specific version of the API used to send the payload body.",
          "type": "string"
        }
      },
      "schema": {
        "$ref": "#/definitions/ErrorInformationResponse"
      }
    },
    "ErrorResponse401": {
      "description": "Unauthorized - The request requires authentication in order to be processed.",
      "headers": {
        "Content-Length": {
          "description": "The Content-Length header field indicates the anticipated size of the payload body. Only sent if there is a body.",
          "type": "integer"
        },
        "Content-Type": {
          "description": "The Content-Type header indicates the specific version of the API used to send the payload body.",
          "type": "string"
        }
      },
      "schema": {
        "$ref": "#/definitions/ErrorInformationResponse"
      }
    },
    "ErrorResponse403": {
      "description": "Forbidden - The request was denied and will be denied in the future.",
      "headers": {
        "Content-Length": {
          "description": "The Content-Length header field indicates the anticipated size of the payload body. Only sent if there is a body.",
          "type": "integer"
        },
        "Content-Type": {
          "description": "The Content-Type header indicates the specific version of the API used to send the payload body.",
          "type": "string"
        }
      },
      "schema": {
        "$ref": "#/definitions/ErrorInformationResponse"
      }
    },
    "ErrorResponse404": {
      "description": "Not Found - The resource specified in the URI was not found.",
      "headers": {
        "Content-Length": {
          "description": "The Content-Length header field indicates the anticipated size of the payload body. Only sent if there is a body.",
          "type": "integer"
        },
        "Content-Type": {
          "description": "The Content-Type header indicates the specific version of the API used to send the payload body.",
          "type": "string"
        }
      },
      "schema": {
        "$ref": "#/definitions/ErrorInformationResponse"
      }
    },
    "ErrorResponse405": {
      "description": "Method Not Allowed - An unsupported HTTP method for the request was used.",
      "headers": {
        "Content-Length": {
          "description": "The Content-Length header field indicates the anticipated size of the payload body. Only sent if there is a body.",
          "type": "integer"
        },
        "Content-Type": {
          "description": "The Content-Type header indicates the specific version of the API used to send the payload body.",
          "type": "string"
        }
      },
      "schema": {
        "$ref": "#/definitions/ErrorInformationResponse"
      }
    },
    "ErrorResponse406": {
      "description": "Not acceptable - The server is not capable of generating content according to the Accept headers sent in the request. Used in the API to indicate that the server does not support the version that the client is requesting.",
      "headers": {
        "Content-Length": {
          "description": "The Content-Length header field indicates the anticipated size of the payload body. Only sent if there is a body.",
          "type": "integer"
        },
        "Content-Type": {
          "description": "The Content-Type header indicates the specific version of the API used to send the payload body.",
          "type": "string"
        }
      },
      "schema": {
        "$ref": "#/definitions/ErrorInformationResponse"
      }
    },
    "ErrorResponse501": {
      "description": "Not Implemented - The server does not support the requested service. The client should not retry.",
      "headers": {
        "Content-Length": {
          "description": "The Content-Length header field indicates the anticipated size of the payload body. Only sent if there is a body.",
          "type": "integer"
        },
        "Content-Type": {
          "description": "The Content-Type header indicates the specific version of the API used to send the payload body.",
          "type": "string"
        }
      },
      "schema": {
        "$ref": "#/definitions/ErrorInformationResponse"
      }
    },
    "ErrorResponse503": {
      "description": "Service Unavailable - The server is currently unavailable to accept any new service requests. This should be a temporary state, and the client should retry within a reasonable time frame.",
      "headers": {
        "Content-Length": {
          "description": "The Content-Length header field indicates the anticipated size of the payload body. Only sent if there is a body.",
          "type": "integer"
        },
        "Content-Type": {
          "description": "The Content-Type header indicates the specific version of the API used to send the payload body.",
          "type": "string"
        }
      },
      "schema": {
        "$ref": "#/definitions/ErrorInformationResponse"
      }
    }
  }
}
